# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Do a buggy test run"
  lane :test do
    run_tests(
      devices: [
        "iPhone 5 (9.3)",
        "iPhone 6 (10.3.1)"
      ]
    )
  end

  desc "Do a working test run"
  lane :workingtest do
    run_tests(
      devices: [
        "iPhone 6 (10.3.1)",
        "iPhone X"
      ]
    )
  end
end
